version: '3.9'

services:
  task-manager-db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: 'always'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE

  task-manager-backend:
    build: .
    depends_on:
      task-manager-db:
        condition: service_healthy
    ports:
      - 3001:3001
    environment:
      - DATABASE_URL=mysql://root:password@task-manager-db:3306/task-manager-test?schema=public
    healthcheck:
      test: ['CMD', 'lsof', '-t', '-i:3001']
      timeout: 10s
      retries: 5
